# Site settings
title: Aosixle
SEOTitle: 键盘侠
header-img: img/post-bg-desk.jpg
email: flyreturn@Outlook.com
description: ""
keyword: "Aosixle,Aosixle Blog"
url: "https://Aosixle.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Aosixle/Aosixle.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "You completely close your mind and do nothing but shout, "Anathema, anathema, anathema!" so that by your own voice you are judged mad!"
sidebar-avatar: /img/about-HJ.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
# zhihu_username:     Aosevle
# github_username:    Aosixle
# facebook_username:  Aosixly
# instagram_username:  Aosixly 
# twitter_username:   Aosixle




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: Aosixle

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: d18b343dd9c7ca49518a                            #生成的clientID
  clientSecret: 539e88b8a7feffaddbb553b9c421dfefcbc6eced    #生成的clientSecret
  repo: Aosixle.github.io    #仓库名称
  owner: Aosixle    #github用户名
  admin: Aosixle
  distractionFreeMode: true #是否启用类似FB的阴影遮罩




